"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { AlertCircle, Check, Plus, RefreshCw, Rocket, Save, ShieldCheck } from "@/components/ui/fa-icon";
import { apiFetch } from "@/lib/api/client";
import { AuditHistory, EmptyState, Field, InlineProblem, OverlayPanel, StatusPill, WorkbenchHeader, areaClass, fieldClass } from "@/modules/commercial/workbench";

type Batch = { id: string; source_label: string; source_key: string; status: string; priority_cohort: boolean; total_rows: number; mapping_version: number; created_at: string };
type Candidate = { id: string; batch_id: string; source_locator: string; record_type: string; normalized_values: Record<string, unknown>; mapping_confidence: number; status: string; trust_tier: string; review_notes: string | null; version: number; open_conflicts: number; updated_at: string };
type Conflict = { id: string; kind: string; detail: string; field_paths: string[]; status: string; resolution: string | null };
type Detail = Candidate & { raw_values: Record<string, unknown>; source_url: string | null; conflicts: Conflict[] };
type Summary = { batches: Batch[]; exceptions: Candidate[]; open_conflicts: number; verified_candidates: number; as_of: string };
type Reconciliation = { batch_id: string; source_label: string; total_rows: number; states: Record<string, number> };

const key = ["commercial", "quality", "summary"] as const;
const commandHeaders = () => ({ "Idempotency-Key": crypto.randomUUID() });

export function MigrationQualityWorkspace() {
  const client = useQueryClient();
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [batchOpen, setBatchOpen] = useState(false);
  const [remapOpen, setRemapOpen] = useState(false);
  const [batchLabel, setBatchLabel] = useState("Notion priority review");
  const [batchJson, setBatchJson] = useState('{"name":"Sample FMCG product","sku":"VHB-SAMPLE-01","unit":"CTN"}');
  const [mappingJson, setMappingJson] = useState("{}");
  const [resolution, setResolution] = useState("Confirmed against source evidence");
  const [error, setError] = useState<unknown>(null);
  const summary = useQuery<Summary>({ queryKey: key, queryFn: () => apiFetch("/commercial/quality/summary") });
  const reconciliation = useQuery<Reconciliation[]>({ queryKey: ["commercial", "quality", "reconciliation"], queryFn: () => apiFetch("/commercial/quality/reconciliation") });
  const effectiveSelectedId = summary.data?.exceptions.some((item) => item.id === selectedId) ? selectedId : summary.data?.exceptions[0]?.id ?? null;
  const detail = useQuery<Detail>({ queryKey: ["commercial", "quality", "candidate", effectiveSelectedId], queryFn: () => apiFetch(`/commercial/quality/candidates/${effectiveSelectedId}`), enabled: Boolean(effectiveSelectedId) });
  const refresh = async () => { await Promise.all([client.invalidateQueries({ queryKey: key }), client.invalidateQueries({ queryKey: ["commercial", "quality", "candidate"] }), client.invalidateQueries({ queryKey: ["commercial", "quality", "reconciliation"] }), client.invalidateQueries({ queryKey: ["commercial", "audit"] })]); };
  const action = useMutation({ mutationFn: async ({ path, body }: { path: string; body?: unknown }) => apiFetch(path, { method: "POST", headers: commandHeaders(), body: body ? JSON.stringify(body) : undefined }), onSuccess: () => { setError(null); void refresh(); }, onError: setError });

  async function createBatch() {
    try { const normalized = JSON.parse(batchJson) as Record<string, unknown>; const result = await apiFetch<Batch>("/commercial/quality/batches", { method: "POST", headers: commandHeaders(), body: JSON.stringify({ source_key: `ui-${Date.now()}`, source_label: batchLabel, priority_cohort: true, rows: [{ source_locator: "UI sample row 1", raw_values: normalized, record_type: "product", normalized_values: normalized, mapping_confidence: 78 }] }) }); setBatchOpen(false); await refresh(); const newest = summary.data?.exceptions.find((item) => item.batch_id === result.id); if (newest) setSelectedId(newest.id); } catch (caught) { setError(caught); }
  }

  const selected = detail.data;
  const verify = () => selected && action.mutate({ path: `/commercial/quality/candidates/${selected.id}/review`, body: { expected_version: selected.version, status: "verified", trust_tier: "verified", review_notes: "Verified in Data Quality Control Center", conflicts: [] } });
  const promote = () => selected && action.mutate({ path: `/commercial/quality/candidates/${selected.id}/promote` });
  const addConflict = () => selected && action.mutate({ path: `/commercial/quality/candidates/${selected.id}/review`, body: { expected_version: selected.version, status: "needs_review", trust_tier: "partially_verified", review_notes: "Conflict created for UI review", conflicts: [{ kind: "source_mismatch", detail: "Normalized value differs from supplied source evidence", field_paths: ["name"] }] } });
  const remap = () => { if (!selected) return; try { action.mutate({ path: `/commercial/quality/candidates/${selected.id}/remap`, body: { expected_version: selected.version, normalized_values: JSON.parse(mappingJson), mapping_confidence: 95, review_notes: "Remapped from Reviewable Foundation UI" } }); setRemapOpen(false); } catch (caught) { setError(caught); } };

  return <div className="flex min-h-full flex-col bg-[#f7f8fa] pb-12">
    <WorkbenchHeader eyebrow="Commercial Data / Quality Control" title="Data Quality Control Center" description="Stage source data, inspect immutable evidence, resolve conflicts, verify mappings and promote trusted records." actions={<><Button variant="outline" size="sm" onClick={() => void refresh()}><RefreshCw className="size-3.5"/>Refresh</Button><Button size="sm" onClick={() => setBatchOpen(true)}><Plus className="size-3.5"/>New batch</Button></>}/>
    <InlineProblem error={error} onRetry={() => setError(null)}/>
    <div className="grid grid-cols-4 border-b bg-background"><Metric label="Open exceptions" value={summary.data?.exceptions.length ?? 0}/><Metric label="Open conflicts" value={summary.data?.open_conflicts ?? 0}/><Metric label="Verified / promoted" value={summary.data?.verified_candidates ?? 0}/><Metric label="Imported batches" value={summary.data?.batches.length ?? 0}/></div>
    <div className="grid min-h-0 flex-1 grid-cols-1 xl:grid-cols-[minmax(540px,1fr)_350px]">
      <section className="min-w-0 overflow-auto border-r bg-background"><div className="flex h-11 items-center justify-between border-b px-4"><div className="flex items-center gap-2"><ShieldCheck className="size-3.5 text-sky-700"/><h2 className="text-xs font-semibold">Exception queue</h2></div><span className="text-[10px] text-muted-foreground">Latest mapping generation only</span></div>{summary.isLoading ? <div className="m-4 h-64 animate-pulse rounded-lg bg-muted"/> : summary.data?.exceptions.length ? <table className="w-full min-w-[720px] text-xs"><thead className="sticky top-0 z-10 bg-slate-50 text-[10px] uppercase tracking-wide text-muted-foreground"><tr><th className="px-4 py-2 text-left">Source record</th><th className="px-3 py-2 text-left">Type</th><th className="px-3 py-2 text-left">Confidence</th><th className="px-3 py-2 text-left">State</th><th className="px-3 py-2 text-left">Updated</th></tr></thead><tbody>{summary.data.exceptions.map((row) => <tr key={row.id} onClick={() => setSelectedId(row.id)} className={`cursor-pointer border-t hover:bg-sky-50/50 ${selectedId === row.id ? "bg-sky-50" : ""}`}><td className="px-4 py-3"><p className="max-w-[320px] truncate font-medium">{String(row.normalized_values.name ?? row.normalized_values.company ?? row.source_locator)}</p><p className="mt-0.5 max-w-[320px] truncate text-[10px] text-muted-foreground">{row.source_locator}</p></td><td className="px-3 py-3 capitalize">{row.record_type}</td><td className="px-3 py-3"><span className={row.mapping_confidence < 90 ? "font-semibold text-amber-700" : "text-emerald-700"}>{row.mapping_confidence}%</span></td><td className="px-3 py-3"><StatusPill value={row.open_conflicts ? `${row.open_conflicts} conflict` : row.status}/></td><td className="px-3 py-3 text-[10px] text-muted-foreground">{new Date(row.updated_at).toLocaleDateString()}</td></tr>)}</tbody></table> : <EmptyState icon="check-double" title="No exceptions waiting" body="Create a batch to generate a reviewable source-data case."/>}
      <div className="border-t bg-slate-50/50 p-4"><div className="mb-2 flex items-center justify-between"><h3 className="text-xs font-semibold">Batch reconciliation</h3><span className="text-[10px] text-muted-foreground">Source rows → candidate states</span></div><div className="grid gap-2 md:grid-cols-2">{reconciliation.data?.map((row) => <div key={row.batch_id} className="rounded-md border bg-background p-3"><div className="flex items-center justify-between"><p className="truncate text-xs font-medium">{row.source_label}</p><span className="text-[10px] text-muted-foreground">{row.total_rows} rows</span></div><div className="mt-2 flex flex-wrap gap-1">{Object.entries(row.states).map(([state, count]) => <span key={state} className="rounded bg-muted px-1.5 py-0.5 text-[9px]">{state.replaceAll("_", " ")}: {count}</span>)}</div></div>)}</div></div></section>
      <aside className="overflow-auto bg-background">{selected ? <><div className="border-b px-4 py-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-[10px] font-medium uppercase tracking-wide text-muted-foreground">Exception detail</p><h2 className="mt-1 truncate text-sm font-semibold">{String(selected.normalized_values.name ?? selected.source_locator)}</h2></div><StatusPill value={selected.status}/></div><p className="mt-2 text-[10px] text-muted-foreground">{selected.source_locator} · mapping v{selected.version}</p><div className="mt-4 grid grid-cols-2 gap-2"><Button size="sm" onClick={verify} disabled={action.isPending || selected.open_conflicts > 0}><Check className="size-3"/>Verify</Button><Button variant="outline" size="sm" onClick={() => { setMappingJson(JSON.stringify(selected.normalized_values, null, 2)); setRemapOpen(true); }}><Save className="size-3"/>Remap</Button><Button variant="outline" size="sm" onClick={addConflict}><AlertCircle className="size-3"/>Create conflict</Button><Button size="sm" onClick={promote} disabled={selected.status !== "verified" || selected.open_conflicts > 0}><Rocket className="size-3"/>Promote</Button></div></div><Evidence title="Normalized mapping" value={selected.normalized_values}/><Evidence title="Immutable source evidence" value={selected.raw_values}/><div className="border-t px-4 py-3"><h3 className="text-xs font-semibold">Conflicts</h3>{selected.conflicts.length ? selected.conflicts.map((conflict) => <div key={conflict.id} className="mt-2 rounded-md border border-amber-200 bg-amber-50 p-3"><div className="flex items-center justify-between"><p className="text-xs font-semibold">{conflict.kind.replaceAll("_", " ")}</p><StatusPill value={conflict.status}/></div><p className="mt-1 text-[11px] leading-5 text-amber-900/80">{conflict.detail}</p>{conflict.status === "open" ? <div className="mt-2 flex gap-2"><input className={fieldClass} value={resolution} onChange={(e) => setResolution(e.target.value)}/><Button size="sm" onClick={() => action.mutate({ path: `/commercial/quality/conflicts/${conflict.id}/resolve`, body: { resolution } })}>Resolve</Button></div> : <p className="mt-2 text-[10px] text-emerald-700">Resolution: {conflict.resolution}</p>}</div>) : <p className="mt-2 text-xs text-muted-foreground">No conflicts recorded.</p>}</div><AuditHistory compact/></> : <EmptyState title="Select an exception" body="Choose a row to inspect evidence and take a governed action."/>}</aside>
    </div>
    {batchOpen ? <OverlayPanel title="Stage a review batch" description="Creates one immutable source row and a low-confidence candidate for UI testing." onClose={() => setBatchOpen(false)}><div className="grid gap-4"><Field label="Source label"><input className={fieldClass} value={batchLabel} onChange={(e) => setBatchLabel(e.target.value)}/></Field><Field label="Raw and normalized sample (JSON)"><textarea className={areaClass} value={batchJson} onChange={(e) => setBatchJson(e.target.value)}/></Field><Button onClick={() => void createBatch()}>Create review batch</Button></div></OverlayPanel> : null}
    {remapOpen ? <OverlayPanel title="Create a new mapping generation" description="The previous candidate is preserved and marked superseded." onClose={() => setRemapOpen(false)}><Field label="Normalized values (JSON)"><textarea className={`${areaClass} min-h-64`} value={mappingJson} onChange={(e) => setMappingJson(e.target.value)}/></Field><Button className="mt-4 w-full" onClick={remap}>Save remapping</Button></OverlayPanel> : null}
  </div>;
}

function Metric({ label, value }: { label: string; value: number }) { return <div className="border-r px-4 py-3 last:border-r-0"><p className="text-[10px] font-medium text-muted-foreground">{label}</p><p className="mt-0.5 text-xl font-semibold tabular-nums">{value}</p></div>; }
function Evidence({ title, value }: { title: string; value: Record<string, unknown> }) { return <div className="border-b px-4 py-3"><h3 className="text-xs font-semibold">{title}</h3><dl className="mt-2 grid gap-1.5">{Object.entries(value).map(([key, item]) => <div key={key} className="grid grid-cols-[110px_1fr] gap-2 text-[11px]"><dt className="truncate text-muted-foreground">{key}</dt><dd className="break-words font-medium">{String(item ?? "—")}</dd></div>)}</dl></div>; }
