"""row links for relations

Revision ID: 4d981267724d
Revises: e19aa8ac5004
Create Date: 2026-06-25 14:53:49.376598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d981267724d'
down_revision: Union[str, Sequence[str], None] = 'e19aa8ac5004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('row_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('source_row_id', sa.Uuid(), nullable=False),
    sa.Column('target_row_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_row_id'], ['rows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_row_id'], ['rows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_id', 'source_row_id', 'target_row_id', name='uq_row_link')
    )
    op.create_index(op.f('ix_row_links_field_id'), 'row_links', ['field_id'], unique=False)
    op.create_index(op.f('ix_row_links_source_row_id'), 'row_links', ['source_row_id'], unique=False)
    op.create_index(op.f('ix_row_links_target_row_id'), 'row_links', ['target_row_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_row_links_target_row_id'), table_name='row_links')
    op.drop_index(op.f('ix_row_links_source_row_id'), table_name='row_links')
    op.drop_index(op.f('ix_row_links_field_id'), table_name='row_links')
    op.drop_table('row_links')
    # ### end Alembic commands ###
