"""field type to varchar

Revision ID: a257836237f4
Revises: b1d9429f018f
Create Date: 2026-06-24 15:41:00.915776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a257836237f4'
down_revision: Union[str, Sequence[str], None] = 'b1d9429f018f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fields', 'type',
               existing_type=postgresql.ENUM('text', 'number', 'checkbox', 'date', 'select', 'url', 'email', 'phone', 'multi_select', 'relation', name='field_type'),
               type_=sa.Enum('text', 'long_text', 'number', 'checkbox', 'date', 'url', 'email', 'phone', 'select', 'multi_select', 'status', 'priority', 'rating', 'relation', name='fieldtype', native_enum=False, length=32),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fields', 'type',
               existing_type=sa.Enum('text', 'long_text', 'number', 'checkbox', 'date', 'url', 'email', 'phone', 'select', 'multi_select', 'status', 'priority', 'rating', 'relation', name='fieldtype', native_enum=False, length=32),
               type_=postgresql.ENUM('text', 'number', 'checkbox', 'date', 'select', 'url', 'email', 'phone', 'multi_select', 'relation', name='field_type'),
               existing_nullable=False)
    # ### end Alembic commands ###
