"""t4 governed masters and pricing

Revision ID: a5c957f239d9
Revises: c3e1d9a7f4b2
Create Date: 2026-08-03 08:45:02.371802

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a5c957f239d9"
down_revision: Union[str, Sequence[str], None] = "c3e1d9a7f4b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customer_accounts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("sales_pic_id", sa.Uuid(), nullable=True),
        sa.Column(
            "lifecycle",
            sa.Enum(
                "active",
                "discontinued",
                "merged",
                name="masterlifecycle",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("merged_into_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["merged_into_id"], ["customer_accounts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["sales_pic_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "name", name="uq_customer_account_name"),
    )
    op.create_index(
        op.f("ix_customer_accounts_lifecycle"), "customer_accounts", ["lifecycle"], unique=False
    )
    op.create_index(op.f("ix_customer_accounts_name"), "customer_accounts", ["name"], unique=False)
    op.create_index(
        op.f("ix_customer_accounts_workspace_id"),
        "customer_accounts",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "fx_rate_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("quote_currency", sa.String(length=3), nullable=False),
        sa.Column("rate", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("effective_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id",
            "base_currency",
            "quote_currency",
            "effective_start",
            name="uq_fx_rate_effective_start",
        ),
    )
    op.create_index(
        op.f("ix_fx_rate_versions_effective_start"),
        "fx_rate_versions",
        ["effective_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fx_rate_versions_workspace_id"), "fx_rate_versions", ["workspace_id"], unique=False
    )
    op.create_table(
        "product_masters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("base_unit", sa.String(length=30), nullable=False),
        sa.Column("origin_country", sa.String(length=2), nullable=True),
        sa.Column("barcode", sa.String(length=100), nullable=True),
        sa.Column("attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "lifecycle",
            sa.Enum(
                "active",
                "discontinued",
                "merged",
                name="masterlifecycle",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("merged_into_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["merged_into_id"], ["product_masters.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "sku", name="uq_product_master_sku"),
    )
    op.create_index(
        op.f("ix_product_masters_created_by_id"), "product_masters", ["created_by_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_masters_lifecycle"), "product_masters", ["lifecycle"], unique=False
    )
    op.create_index(op.f("ix_product_masters_name"), "product_masters", ["name"], unique=False)
    op.create_index(
        op.f("ix_product_masters_workspace_id"), "product_masters", ["workspace_id"], unique=False
    )
    op.create_table(
        "supplier_masters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("supplier_code", sa.String(length=100), nullable=True),
        sa.Column(
            "lifecycle",
            sa.Enum(
                "active",
                "discontinued",
                "merged",
                name="masterlifecycle",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("merged_into_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["merged_into_id"], ["supplier_masters.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "name", name="uq_supplier_master_name"),
    )
    op.create_index(
        op.f("ix_supplier_masters_lifecycle"), "supplier_masters", ["lifecycle"], unique=False
    )
    op.create_index(op.f("ix_supplier_masters_name"), "supplier_masters", ["name"], unique=False)
    op.create_index(
        op.f("ix_supplier_masters_workspace_id"), "supplier_masters", ["workspace_id"], unique=False
    )
    op.create_table(
        "customer_contacts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("customer_account_id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("consent", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_account_id"], ["customer_accounts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_customer_contacts_customer_account_id"),
        "customer_contacts",
        ["customer_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_contacts_workspace_id"),
        "customer_contacts",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "legal_parties",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("customer_account_id", sa.Uuid(), nullable=False),
        sa.Column("legal_name", sa.String(length=300), nullable=False),
        sa.Column("tax_identifier", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_account_id"], ["customer_accounts.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "tax_identifier", name="uq_legal_party_tax_identifier"),
    )
    op.create_index(
        op.f("ix_legal_parties_customer_account_id"),
        "legal_parties",
        ["customer_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_legal_parties_workspace_id"), "legal_parties", ["workspace_id"], unique=False
    )
    op.create_table(
        "product_price_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("input_cost", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("fx_rate", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("logistics_cost", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("tax_cost", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("margin_percent", sa.Numeric(precision=9, scale=4), nullable=False),
        sa.Column("proposed_price", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("approved_price", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("method", sa.String(length=50), nullable=False),
        sa.Column("incoterm", sa.String(length=20), nullable=True),
        sa.Column("effective_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "approved",
                "oral_pending",
                "rejected",
                name="pricestatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("approval_note", sa.Text(), nullable=True),
        sa.Column("approved_by_id", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["approved_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["product_id"], ["product_masters.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_price_versions_effective_start"),
        "product_price_versions",
        ["effective_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_price_versions_product_id"),
        "product_price_versions",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_price_versions_status"), "product_price_versions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_product_price_versions_workspace_id"),
        "product_price_versions",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_migration_batches_asset_id"), "migration_batches", ["asset_id"], unique=False
    )
    op.create_index(
        op.f("ix_migration_batches_assigned_to_id"),
        "migration_batches",
        ["assigned_to_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_migration_batches_created_by_id"),
        "migration_batches",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_migration_promotion_receipts_created_at"),
        "migration_promotion_receipts",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_migration_promotion_receipts_created_at"),
        table_name="migration_promotion_receipts",
    )
    op.drop_index(op.f("ix_migration_batches_created_by_id"), table_name="migration_batches")
    op.drop_index(op.f("ix_migration_batches_assigned_to_id"), table_name="migration_batches")
    op.drop_index(op.f("ix_migration_batches_asset_id"), table_name="migration_batches")
    op.drop_index(
        op.f("ix_product_price_versions_workspace_id"), table_name="product_price_versions"
    )
    op.drop_index(op.f("ix_product_price_versions_status"), table_name="product_price_versions")
    op.drop_index(op.f("ix_product_price_versions_product_id"), table_name="product_price_versions")
    op.drop_index(
        op.f("ix_product_price_versions_effective_start"), table_name="product_price_versions"
    )
    op.drop_table("product_price_versions")
    op.drop_index(op.f("ix_legal_parties_workspace_id"), table_name="legal_parties")
    op.drop_index(op.f("ix_legal_parties_customer_account_id"), table_name="legal_parties")
    op.drop_table("legal_parties")
    op.drop_index(op.f("ix_customer_contacts_workspace_id"), table_name="customer_contacts")
    op.drop_index(op.f("ix_customer_contacts_customer_account_id"), table_name="customer_contacts")
    op.drop_table("customer_contacts")
    op.drop_index(op.f("ix_supplier_masters_workspace_id"), table_name="supplier_masters")
    op.drop_index(op.f("ix_supplier_masters_name"), table_name="supplier_masters")
    op.drop_index(op.f("ix_supplier_masters_lifecycle"), table_name="supplier_masters")
    op.drop_table("supplier_masters")
    op.drop_index(op.f("ix_product_masters_workspace_id"), table_name="product_masters")
    op.drop_index(op.f("ix_product_masters_name"), table_name="product_masters")
    op.drop_index(op.f("ix_product_masters_lifecycle"), table_name="product_masters")
    op.drop_index(op.f("ix_product_masters_created_by_id"), table_name="product_masters")
    op.drop_table("product_masters")
    op.drop_index(op.f("ix_fx_rate_versions_workspace_id"), table_name="fx_rate_versions")
    op.drop_index(op.f("ix_fx_rate_versions_effective_start"), table_name="fx_rate_versions")
    op.drop_table("fx_rate_versions")
    op.drop_index(op.f("ix_customer_accounts_workspace_id"), table_name="customer_accounts")
    op.drop_index(op.f("ix_customer_accounts_name"), table_name="customer_accounts")
    op.drop_index(op.f("ix_customer_accounts_lifecycle"), table_name="customer_accounts")
    op.drop_table("customer_accounts")
    # ### end Alembic commands ###
