"""row seq and order

Revision ID: e19aa8ac5004
Revises: a257836237f4
Create Date: 2026-06-25 09:57:04.152716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e19aa8ac5004'
down_revision: Union[str, Sequence[str], None] = 'a257836237f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'rows',
        sa.Column('seq', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column(
        'rows',
        sa.Column('order', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rows', 'order')
    op.drop_column('rows', 'seq')
    # ### end Alembic commands ###
